version: '2'
services:
    session4-app:
        image: session4
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://session4-postgresql:5432/Session4
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    session4-postgresql:
        extends:
            file: postgresql.yml
            service: session4-postgresql
